### ISSUE TITLE
2.0.1 broken in PhantomJS 2.1

### ISSUE THREAD

**Issue by dpogue** [dumbmatter/fakeIndexedDB#19]
I know, we all love supporting PhantomJS and it's terrible old buggy APIs, but our main reason for using fakeIndexedDB is to work around Phantom's horrifically buggy indexedDB implementation 😞 

```
TypeError: undefined is not a constructor (evaluating 'Array.from(rawDatabase.rawObjectStores.keys())')
```

Looks like it's caused by https://github.com/dumbmatter/fakeIndexedDB/blob/8547e5739cd6083afc9a6d1a393f8b9460d98751/src/FDBDatabase.ts#L77, which I'm guessing is due to `Array.from` not existing

**Comment by dumbmatter** [comment]
Yeah I was thinking people can include polyfills for stuff like that, but I guess it's better if I do that out of the box, since it's not like bundle size matters for this library. v2.0.2 includes core-js so it should work fine. `npm run test-qunit` does use PhantomJS - previously it was manually including a polyfill library, but now it isn't and it still works.

**Comment by dpogue** [comment]
Thanks!

There's definitely an awkward lose-lose situation affecting a bunch of projects with people complaining that the module is bloated by including a bunch of duplicated polyfills, and people also complaining that the module doesn't work because it doesn't bundle polyfills. 😞
