### ISSUE TITLE
InvalidStateError when parallely opening a db that needs a versionchange transaction

### ISSUE THREAD

**Issue by julienw** [dumbmatter/fakeIndexedDB#22]
Here is a STR:
```
var indexedDB = require("fake-indexeddb");

function openDb() {
  return new Promise((resolve, reject) => {
    var request = indexedDB.open("test", 3);
    request.onupgradeneeded = function () {
      var db = request.result;
      var store = db.createObjectStore("books", {keyPath: "isbn"});
    }
    request.onsuccess = function (event) {
      var db = event.target.result;
      resolve(db);
    };
  });
}

openDb();

openDb().then(db => {
  db.transaction("books");
  console.log('All good!');
});
```

You can clone the repository here: https://github.com/julienw/fake-indexeddb-bug

You can also see it live (open the Devtools' console to see it, as the page itself is blank):
* with [fake-indexedDB](https://julienw.github.io/fake-indexeddb-bug/fake-index.html)
* with [in-browser indexedDB](https://julienw.github.io/fake-indexeddb-bug/) (working!)

**Comment by julienw** [comment]
From what I investigated, I could see that the "versionchange" transaction wasn't properly finished in this case.

Everything works fine when we remove the first open requests, or when we chain the open requests.

**Comment by dumbmatter** [comment]
Thanks for the awesome bug report! It'll be at least a couple days until I have a chance to look into this, but I'll try to do it this weekend at the latest.

**Comment by julienw** [comment]
I tried to fix it myself but couldn't find my way in the code :) if you have an idea where the fix could be I can have a look !

**Comment by dumbmatter** [comment]
It's probably in FDBDatabase.ts. I know some of that is not 100% standards compliant, particularly related to opening the same database multiple times like in your example, but I don't know exactly where the bug is. I think some of the W3C tests fail for this reason. Most people just open the database once, so I didn't worry too much about it.

**Comment by dumbmatter** [comment]
Sorry, FDBFactory.ts, not FDBDatabase.ts :)

**Comment by dumbmatter** [comment]
The error is from [step 1 here](https://w3c.github.io/IndexedDB/#dom-idbdatabase-transaction):

> If a running upgrade transaction is associated with the connection, throw an "InvalidStateError" DOMException.

Instead of doing it for "the connection", fakeIndexedDB was doing it for "any connection".

I'm not totally sure why the upgrade transaction from the first conection is still running by the time the second onsuccess is called. That could be a deeper problem. But if this simple fix makes your problem go away, I'll do a new release. Does it work for you?

**Comment by julienw** [comment]
I don't have the problem anymore as it was in tests and I could rearrange them to test the same thing without producing the error. So feel free to take the time to investigate this properly if you need it :)
