### ISSUE TITLE
Consider adding TransactionInactiveError

### ISSUE THREAD

**Issue by jcalfee** [dumbmatter/fakeIndexedDB#3]
I see an InvalidStateError from nodejs.  When I run the same thing in chrome I get a TransactionInactiveError.

WEB Reports:  `DOMException: Failed to execute 'add' on 'IDBObjectStore': The transaction is not active.`

Node and fake index db (matching InvalidStateError from the spec): `An operation was called on an object on which it is not allowed or at a time when it is not allowed. Also occurs if a request is made on a source object that has been deleted or removed. Use TransactionInactiveError or ReadOnlyError when possible, as they are more specific variations of InvalidStateError.' `

**Comment by dumbmatter** [comment]
This works for me, it throws a TransactionInactiveError:

    var fakeIndexedDB = require('fake-indexeddb');

    var request = fakeIndexedDB.open('test');
    request.onupgradeneeded = function () {
        var db = request.result;
        db.createObjectStore("test");
    }
    request.onsuccess = function (event) {
        var db = event.target.result;

        var tx = db.transaction("test", "readwrite");
        var objectStore = tx.objectStore("test");

        setTimeout(function () {
            objectStore.add({a: 1});
        }, 10);
    };

However if I move the tx.objectStore call inside the async function like this:

    var fakeIndexedDB = require('fake-indexeddb');

    var request = fakeIndexedDB.open('test');
    request.onupgradeneeded = function () {
        var db = request.result;
        db.createObjectStore("test");
    }
    request.onsuccess = function (event) {
        var db = event.target.result;

        var tx = db.transaction("test", "readwrite");

        setTimeout(function () {
            tx.objectStore("test").add({a: 1});
        }, 10);
    };

then I do get an InvalidStateError. Which I think is correct, since [the spec says](http://www.w3.org/TR/IndexedDB/#widl-IDBTransaction-objectStore-IDBObjectStore-DOMString-name) "If the transaction has finished, the implementation MUST throw a DOMException of type InvalidStateError."

I know that in cases when there are multiple exceptions not all browsers throw them in exactly the same order, but Chrome seems to do the same as fakeIndexedDB in this case.

If you're seeing a problem, can you post code?
