### ISSUE TITLE
setTimeout problems / questions

### ISSUE THREAD

**Issue by joshkel** [dumbmatter/fakeIndexedDB#69]
I'm having some problems since the upgrade to 3.1.4; Jest tests that previously worked fine are now timing out. I did some digging, and if I understand correctly:

* Starting with 3.1.4, fake-indexeddb uses `setTimeout` instead of `setImmediate`.
* In Node.js, setTimeout enforces a [minimum delay of 1ms](https://nodejs.org/api/timers.html#timers_settimeout_callback_delay_args), so every fake-indexeddb operation takes at least 1 millisecond.
* On Windows, from what I can tell, the Node.js timer has a resolution of ~15ms, so every fake-indexeddb operation takes at least 15 milliseconds.
* jsdom uses Node.js's setTimeout implementation unchanged, so all of the above applies in jsdom test environments as well.

I experimented with using Jest's fake timers to speed up my tests, but they don't appear to be a great solution: because IndexedDB operations result in fake-indexeddb timers which resolve promises which may then trigger additional IndexedDB operations (etc.), there's an awkward dance of trying to figure out which timers and promises are outstanding after each operation so that they can all be properly resolved. (See the linked test case for an example of what this looks like - this gets even harder when using third-party code that may do multiple IndexedDB operations in a row. Maybe there's an easier way to do this in Jest? If so please let me know.)

We ran into this using the [idb-keyval](https://github.com/jakearchibald/idb-keyval) package, which, in order to keep a simple API, relies on lots of small operations.

Test case: https://github.com/joshkel/fake-indexeddb-settimeout-test-case

Timings for the "create and read a bunch of values" from that project in fake-indexeddb 3.1.4:

* macOS, Node.js 14.17.1 - 71 ms
* Windows, Node.js 14.17.0 - 54 ms

In fake-indexeddb 3.1.3:

* macOS, Node.js 14.17.1 - 734 ms
* Windows, Node.js 14.17.0 - 6734 ms

**Comment by dumbmatter** [comment]
Thanks for looking into this. I'm really not sure what the best solution is here, but let me try to summarize the problem as I understand it:

- jsdom breaks setImmediate, so that can't be used, as described in #67
- setTimeout is very slow on Windows, so that can't be used

#68 by @ph-fritsche would make it configurable whether to use setTimeout or setImmediate. But that would still not help for people facing both of the problems above - they could only fix one of those problems, not both.

There must be a better solution. Off the top of my head, I'm not sure what that is. But if someone could figure out how to either:

- successfully use setImmediate and jsdom together, or
- find a better way to run a macrotask in a way that is faster than setTimeout and not interfered with by jsdom (process.nextTick won't work, it's too fast!)

then that would allow me to fix this issue for all cases.

**Comment by dumbmatter** [comment]
Fixed in v3.1.6, thank you @joshkel and everyone else who helped debug this!
